{
 "title": "VM-GPU-v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket Name", "query": "HHLL" }
  ]
 },
 "panels": [
  { "title": "GPU metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "CUDA Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cuda_version\")\r\n  |> group()\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"driver_version\")\r\n  |> group()\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_gpu\")\r\n  |> group()\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Graphic Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"clocks_current_graphics\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"clocks_current_memory\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Video Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"clocks_current_video\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_used\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_total\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"utilization_gpu\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"utilization_memory\")\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PCIe Link Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\") |> filter(fn: (r) => r[\"_field\"] == \"pcie_link_gen_current\") |> group() |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false) |> yield(name: \"max\")"
    },
    {
     "query": "from(bucket: \"${bucket}\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\") |> filter(fn: (r) => r[\"_field\"] == \"pcie_link_width_current\") |> group() |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false) |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Video Logic Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\") |> filter(fn: (r) => r[\"_field\"] == \"utilization_encoder\") |> group() |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket}\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\") |> filter(fn: (r) => r[\"_field\"] == \"utilization_decoder\") |> group() |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Active GPU Processes",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi_process\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_memory\")\n  |> map(fn: (r) => ({ r with _value: int(v: strings.trimSpace(v: r._value)) }))\n  |> group(columns: [\"pid\", \"process_name\"])\n  |> last()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> keep(columns: [\"pid\", \"process_name\", \"_value\"])"
    }
   ]
  },
  { "title": "eBPF Network Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Top Process Network Usage",
   "type": "bargauge",
   "description": "Process consuming most bandwidth (Upload + Download)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tcp_top\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_kb\" or r[\"_field\"] == \"rx_kb\")\r\n  |> group(columns: [\"comm\"])\r\n  |> sum()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "bargauge",
   "description": "Top Destination Ports being accessed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tcp_top\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_kb\" or r[\"_field\"] == \"rx_kb\")\r\n  |> group(columns: [\"dport\"])\r\n  |> sum()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Top Remote IPs",
   "type": "bargauge",
   "description": "Remote IPs interacting the most",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tcp_top\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_kb\" or r[\"_field\"] == \"rx_kb\")\r\n  |> group(columns: [\"raddr\"])\r\n  |> sum()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Live Network Traffic Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tcp_top\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_kb\" or r[\"_field\"] == \"rx_kb\")\r\n  // Dòng quan trọng: Pivot để xoay dữ liệu, đưa Tag và Field lên cùng 1 hàng\r\n  |> pivot(rowKey:[\"_time\", \"pid\", \"comm\", \"raddr\", \"dport\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  // Bỏ group để hiện toàn bộ danh sách phẳng\r\n  |> group()\r\n  // Xóa các cột rác không cần thiết\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"host\", \"laddr\", \"lport\"])\r\n  // Sắp xếp theo thời gian mới nhất\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  // Lấy 50 dòng đầu tiên\r\n  |> limit(n: 50)"
    }
   ]
  }
 ]
}